rpmsg: imx: include slab.h explicitly
To fix build issues of:
error: implicit declaration of function ‘kmalloc’
error: implicit declaration of function ‘kfree’

Signed-off-by: Li Yang <leoyang.li@nxp.com>
(cherry picked from commit b2432a6607694e81fa6709338b7d453a91ce70a7)
Signed-off-by: LI Qingwu <Qing-wu.Li@leica-geosystems.com.cn>